wallet:
  transaction_signup: "Signup"
  transaction_commit: "Commit"
  signup_amount: 500
  subscription_amount: 150
  challenge_subscription: "Challenge Subscription"

round:
  states: {"inactive":"inactive","open":"open","close":"close"}

messages:
  already_subscribed: "You have already subscribed for this challenge"
  insufficient_points: "You have insufficient points for this transaction"
  login_required: "You must signin/signup to continue"
