wallet:
  transaction_signup: Signup
  transaction_commit: Commit
  signup_amount: 500
  subscription_amount: 150
  challenge_subscription: Challenge Subscription

round:
  states: 
    inactive: inactive
    open: open
    close: close

repository:
  popular: 
    stars: 25

user:
  :royalty_points_threshold: 50_000

scoring_engine:
  :repositories: 'repositories' # repositories dir
  :max_score: 5
  :code_lines_to_points: 10
  :code_change_threshold: 200
  :code_change_threshold_score: 1
  :comments_to_points: 3
  :commit_comments_weightage: 0.1
  :commit_default_weightage: 0.45
  :bugspot_weightage: 0.45

retailers:
  - Github
  - Amazon
