# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2b9b33466ea6a408a69f7785c1ba391cadef27691810de33fc79606c619d5e5cd3d95b5655efed14b9ad914c19750692b238d078ae57a03df46b963e8f99fbd
  redeem_request_emails: ['gautma@joshsoftware.com']

test:
  secret_key_base: 8425803cd5586d11bd05b2db1b87bd4f171da1a7f4fb668ff01df5f7e2d55ccbb63d9129ffe4d5168502d89e400b496f6d2c5886d2bbe9242e9c29ab4f78eeb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
