groups:
  1:
    name: Horses
    desc: Prancing among the horses
    default: true
  2:
    name: Wolves
    desc: Dancing with wolves
    followers: 5
    own_repositories: 
      count: 1
      stars: 15
    popular_repositories:
      count: 1
      stars: 25
  3:
    name: Eagles
    desc: Flying with the eagles
    followers: 15
    repositories: 
      count: 2
      stars: 25 
    popular_repositories:
      count: 2
      stars: 75
